### ISSUE TITLE
AttributeError: 'FFmpegOpusAudio' object has no attribute '_process'

### ISSUE THREAD

**Issue by Kolhax** [mytja/harmonoid-music-bot#7]
Exception ignored in: <function AudioSource.__del__ at 0x000001AEB38384C0>
Traceback (most recent call last):
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\player.py", line 118, in __del__
    self.cleanup()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\player.py", line 224, in cleanup
    self._kill_process()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\player.py", line 189, in _kill_process
    proc = self._process
AttributeError: 'FFmpegOpusAudio' object has no attribute '_process'

**Comment by mytja** [comment]
Can you please pull latest version from Git and re-fetch dependencies using `pip install -r requirements.txt`

**Comment by Kolhax** [comment]
```
C:\Users\my-pc2\Downloads\music bot\harmonoid-music-bot>py main.py
Traceback (most recent call last):
  File "C:\Users\my-pc2\Downloads\music bot\harmonoid-music-bot\main.py", line 1, in <module>
    from commands import *
  File "C:\Users\my-pc2\Downloads\music bot\harmonoid-music-bot\commands\__init__.py", line 1, in <module>
    import discord
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\__init__.py", line 25, in <module>
    from .client import Client
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 53, in <module>
    from .webhook import Webhook
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook\__init__.py", line 12, in <module>
    from .async_ import *
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook\async_.py", line 46, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py)

C:\Users\my-pc2\Downloads\music bot\harmonoid-music-bot>
```

**Comment by mytja** [comment]
This is certainly weird. I do not recommend installing it barebones on your system, but rather using stable Docker image.

We are still confused from `pycord` migration, but as I've tested it, it works on my system.
I certainly cannot guess what's issue with your system. Maybe you have installed `discord.py` and `pycord`. Maybe you have too old version of `pycord`. In any case I'd suggest you to update packages or rather use Docker image in WSL or HyperV (for Windows).

Thank you so much

**Comment by mytja** [comment]
Closing. It's working as of the newest release (at least in the latest Docker image). Please open a new issue in case of any further issues.
